### ISSUE TITLE
Make the site Responsive

### ISSUE THREAD

**Issue by Subhradeep10** [Subhradeep10/Fitnezz#1]
The site is not responsive, Need some on to make it

**Comment by Yusuf-gitCollab** [comment]
Hi I can help you make this site responsive. Can I take this issue and work on it?

**Comment by Subhradeep10** [comment]
@Yusuf-gitCollab Assigned to you.

**Comment by Yusuf-gitCollab** [comment]
@Subhradeep10  apart from Home.css do you have any other stylesheet linked. I am getting some weird styling even after removing the styling .

**Comment by Yusuf-gitCollab** [comment]
And if possible can we talk on discord as it is easier to send images there. 
this is the link to my discord pls follow: [https://discord.gg/dJUntm4N](url)

**Comment by Subhradeep10** [comment]
@Yusuf-gitCollab Yes , I have added bootstrap. If you want , you can remove it
