### ISSUE TITLE
1.Change the animation on Join Today, Join Now and Register Buttons.

### ISSUE THREAD

**Issue by Ashxsh1** [Subhradeep10/Fitnezz#102]

**Comment by Atharv-110** [comment]
Go ahead @Ashxsh1
Assigned to you!

**Comment by MohitNamdev22** [comment]
@Ashxsh1 Are you still working on it?

**Comment by Ashxsh1** [comment]
Yep!
Due to some important work it is getting delayed, Ill finish it ASAP.
