### ISSUE TITLE
Update the navigation section with suitable names

### ISSUE THREAD

**Issue by zugzwang03** [Subhradeep10/Fitnezz#103]
The navigation section contains home, about, contact, news; but in reality the website layout is home, featured classes, scheduled classes, trainee and registration section. I want to update this navigation links with suitable links on it.
![image](https://user-images.githubusercontent.com/95460021/182996476-e4c4e2ce-ac53-4124-b27e-8f96a32d959c.png)

**Comment by zugzwang03** [comment]
Also I want to work on this issue under SSOC'22

**Comment by Subhradeep10** [comment]
@zugzwang03 About pages and other words pages are also coming, the featured classes are the components of Home page
