### ISSUE TITLE
Add Free class button in navbar

### ISSUE THREAD

**Issue by con-artist** [Subhradeep10/Fitnezz#108]
![image](https://user-images.githubusercontent.com/82517773/183090818-e5d54bf7-5f5d-49cf-848a-a8eba678c7fd.png)
Next to "become a member " option I want to add a "Free class" option which when clicked will take you to the register section in the page 
![image](https://user-images.githubusercontent.com/82517773/183091058-07dd567e-ffe6-42cb-a997-326174437ca5.png)
something like this

**Comment by Subhradeep10** [comment]
@con-artist Not needed
