### ISSUE TITLE
Adding Back workout page

### ISSUE THREAD

**Issue by kshitijmishra27** [Subhradeep10/Fitnezz#112]
hi @Subhradeep10 
issues of an arm workout, leg workout, and chest workout are already raised so I will like to work on the Back workout page
on clicking the Backworkout card...user will be directed to the Back-workout page
waiting for you to assign me 😄

**Comment by TusharKesarwani** [comment]
@kshitijmishra27 Go ahead

**Comment by TusharKesarwani** [comment]
Any updates??

**Comment by TusharKesarwani** [comment]
I'm closing this issue
As it was already done by another contributor
And contribution phase is ending soon.
