### ISSUE TITLE
Refactor the code to remove redundancy 

### ISSUE THREAD

**Issue by con-artist** [Subhradeep10/Fitnezz#116]
All the workout cards have been coded separately. 
![image](https://user-images.githubusercontent.com/82517773/183226730-0f2e2ee1-7861-4aa8-80f0-e95068c9074c.png)

I have to add them in another file and map through them

**Comment by TusharKesarwani** [comment]
Please mention what is the benefit of doing this @con-artist

**Comment by con-artist** [comment]
Basically In future if you have to add more cards or workouts you wont have to a write code for each card and it will reduce the number of lines of code also .

**Comment by TusharKesarwani** [comment]
Ok @con-artist Go ahead

**Comment by con-artist** [comment]
@TusharKesarwani  can you assign it please.
