### ISSUE TITLE
in join page i think its ui can be made a little better like the join form it can be improved i like to do it

### ISSUE THREAD

**Issue by vaibhavsharma1234** [Subhradeep10/Fitnezz#121]

**Comment by TusharKesarwani** [comment]
@vaibhavsharma1234 GO ahead

**Comment by vaibhavsharma1234** [comment]
![nav](https://user-images.githubusercontent.com/96341386/183917671-e80aa09b-e256-4c08-8658-707ebded9568.png)
should i keep this nav bar or u want me to have ur navbar only

**Comment by vaibhavsharma1234** [comment]
i think i should keep the navbar in the picture because i tried to keep the other navabr nut its affecting the whole join page

**Comment by vaibhavsharma1234** [comment]
how does it look ?
![new-join](https://user-images.githubusercontent.com/96341386/183976272-2b9327c8-f828-43fa-a75e-93cca7882af6.png)
any changes u want or should i make a pr

**Comment by TusharKesarwani** [comment]
Now you can make PR @vaibhavsharma1234

**Comment by vaibhavsharma1234** [comment]
i will make once the layout is resolved

**Comment by TusharKesarwani** [comment]
> i will make once the layout is resolved or should i make now

Now you can make PR

**Comment by vaibhavsharma1234** [comment]
completed thanks
