### ISSUE TITLE
Fixing navbar to stay at top

### ISSUE THREAD

**Issue by Aman-Singh-Kushwaha** [Subhradeep10/Fitnezz#123]
Hey @mentors it will look cool when the navbar stays on top of the screen while scrolling

**Comment by Aman-Singh-Kushwaha** [comment]
So, Assign it to me

**Comment by TusharKesarwani** [comment]
@Aman-Singh-Kushwaha Go ahead

**Comment by Aman-Singh-Kushwaha** [comment]
Completed
