### ISSUE TITLE
Fix navbar button in join in page

### ISSUE THREAD

**Issue by con-artist** [Subhradeep10/Fitnezz#126]
![image](https://user-images.githubusercontent.com/82517773/183245719-0490b6d2-ecb1-4ddb-965f-9aca85cd5e7f.png)
The expand navbar icon is not working. I would like to  fix it. Please assign it to me

**Comment by TusharKesarwani** [comment]
It is working properly.
The join-in page is already available in the footer of the website.
Please visit the website again @con-artist

**Comment by con-artist** [comment]
https://subhradeep10.github.io/Fitnezz/joinin.html#
If you go to this page and reduce the size to mobile view you will the nav is not opening 
I tried it and its not working.

**Comment by TusharKesarwani** [comment]
Ok,
@con-artist Go ahead and work on this.
I'm assigning it to you.
