### ISSUE TITLE
Align registration form in right place 

### ISSUE THREAD

**Issue by Ashish4321-hub** [Subhradeep10/Fitnezz#127]
The registration form are not aligned properly .So l want to align properly.
![Screenshot_2022-08-06-19-01-26-55_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/88235823/183251180-d916f85b-67d9-4e46-98d0-327eadea33b2.jpg)

**Comment by TusharKesarwani** [comment]
It is working properly.
Please zoom out of the page.
Or visit the website again on chrome on a new tab.

**Comment by Ashish4321-hub** [comment]
Okay sir
