### ISSUE TITLE
Improving the font size, weight and transition of home page 

### ISSUE THREAD

**Issue by Vanshiii203** [Subhradeep10/Fitnezz#140]
![Screenshot (287)](https://user-images.githubusercontent.com/94471189/183350956-ba49033f-b9d7-46f4-98e2-0395a0069399.png)

**Comment by akanksha0812** [comment]
Please assign this issue to me, i will do the required changes

**Comment by TusharKesarwani** [comment]
@Vanshiii203 Go ahead and make changes
