### ISSUE TITLE
Improve the Slider in Testimonial Section

### ISSUE THREAD

**Issue by Atharv-110** [Subhradeep10/Fitnezz#144]
Sliders include left-right button sliders, toggle sliders, grab the content, and slide.
Please Improve the testimonial slider by implementing the above types in all.
Anyone who wishes to work on this issue, comment down and it will be assigned to them.

**Comment by vaibhavsharma1234** [comment]
I can take it but i didn't understand what to do

**Comment by vaibhavsharma1234** [comment]
I can add automatic slider Plus the arrow or toggle one

**Comment by vaibhavsharma1234** [comment]
But i don't know how to add geav the content one

**Comment by Atharv-110** [comment]
@vaibhavsharma1234 got for it. Try to go through the resources for implementing grab functionality amongst cards.
Assigned to you.

**Comment by con-artist** [comment]
@Atharv-110  I don't see any testimonials section on the website? And  any idea why are the changes from merged pull requests not begin shown in the deployed website?

**Comment by vaibhavsharma1234** [comment]
It's because the build is failing during deployment
That's why changes are in code but not on website

**Comment by con-artist** [comment]
@vaibhavsharma1234  Even in my local after pulling I dont see any testimonial section? Is it there for you?

**Comment by vaibhavsharma1234** [comment]
yes someone removed the testimonial  section 
@Atharv-110  should i add one ?

**Comment by Atharv-110** [comment]
@vaibhavsharma1234 there is a testimonial section but it didn't update on build check on your local deployment

**Comment by vaibhavsharma1234** [comment]
completed thanks
