### ISSUE TITLE
Transition in Navbar ul is not smooth

### ISSUE THREAD

**Issue by MohitNamdev22** [Subhradeep10/Fitnezz#150]
The transition on Navbar ul is not smooth, and I wish to Fix this issue under SSOC'22. So can you Assign it to me?
![image](https://user-images.githubusercontent.com/89779447/183567146-be347f6f-ab72-44fb-b471-a00f0f4cee5c.png)

**Comment by TusharKesarwani** [comment]
Go ahead @MohitNamdev22
