### ISSUE TITLE
Fix UI of page

### ISSUE THREAD

**Issue by con-artist** [Subhradeep10/Fitnezz#153]
The whole UI seems to have become messed up because of a bad PR. I would like to fix things
![image](https://user-images.githubusercontent.com/82517773/183788630-e7c500ea-7854-4f73-88bd-22c520d27e1c.png)
![image](https://user-images.githubusercontent.com/82517773/183788657-5aa17e7a-a1de-45a3-86b2-0f1deb1f423f.png)
![image](https://user-images.githubusercontent.com/82517773/183788681-86f07c0a-4d20-460e-b6c9-167cfb8749ee.png)
![image](https://user-images.githubusercontent.com/82517773/183788691-842c418a-f15e-42fb-9f2a-de84e16419b0.png)

**Comment by Subhradeep10** [comment]
@con-artist Go ahead, assigned to you
