### ISSUE TITLE
Improve the FAQs section

### ISSUE THREAD

**Issue by zugzwang03** [Subhradeep10/Fitnezz#158]
Most of the questions in the FAQ section contains dummy text or irrelevant answers. I want to work on correcting those places under SSOC'22. 
![incorrectquestion](https://user-images.githubusercontent.com/95460021/183824014-b0dc4c30-7c3f-44cd-b271-2c1d1c9e8ba5.png)
![typos](https://user-images.githubusercontent.com/95460021/183824035-2278238e-8254-448e-97d4-b4f08f2397e6.png)

**Comment by Atharv-110** [comment]
sure go ahead @zugzwang03, Assigned to you!
