### ISSUE TITLE
Image fixation in Pictures

### ISSUE THREAD

**Issue by zugzwang03** [Subhradeep10/Fitnezz#162]
The faces of the trainees are not visible in the "Meet the Trainers" section. I want to fix this issue under SSOC'22.

![imagefix](https://user-images.githubusercontent.com/95460021/184063175-515c1faf-c293-4eb6-9176-1b06a4a60736.png)
![face](https://user-images.githubusercontent.com/95460021/184063243-81f51c70-1729-405e-a154-6a78860a5a7f.png)

**Comment by TusharKesarwani** [comment]
Go ahead @zugzwang03
