### ISSUE TITLE
Validation of all entries in registration form

### ISSUE THREAD

**Issue by tushar-glitch** [Subhradeep10/Fitnezz#163]
Please assign me this issue. I can work on this.

**Comment by Subhradeep10** [comment]
@tushar-glitch How will you do this?

**Comment by tushar-glitch** [comment]
@Subhradeep10 
- For the name, I will check that the input doesn't contain any numbers or special symbols.
- For gender, Maybe I can add 3 radio options -Male, Female and Others
- I will check for a valid email syntax
- Maybe more options that will come along the way

**Comment by Atharv-110** [comment]
This same issue have been already assigned please check all the issues.
