### ISSUE TITLE
Fix UI of the Home Page

### ISSUE THREAD

**Issue by con-artist** [Subhradeep10/Fitnezz#165]
The whole UI is messed up again because of the Last PR that was merged.
I would like to fix it. Please assign me

**Comment by Subhradeep10** [comment]
@con-artist go ahead

**Comment by con-artist** [comment]
@Subhradeep10 @vaibhavsharma1234  This happens because people don't "git pull"  before making a PR because which they end up having conflicts that they don't resolve properly. Also with netlifly you can see the preview of the website before merging the PR so why do you merge the PR in the first place? 
This issue happened because of the last PR that was merged.
https://github.com/Subhradeep10/Fitnezz/pull/161 You shouldn't have merged this PR

**Comment by con-artist** [comment]
Anyways, it gives me a free issue to solve so 😂

**Comment by TusharKesarwani** [comment]
This is completed by another contributor.
