### ISSUE TITLE
Replace the logo in Navbar

### ISSUE THREAD

**Issue by Atharv-110** [Subhradeep10/Fitnezz#170]
The logo in the navbar is a normal text. Someone who can replace that text with the image given in the link below.

[https://subhradeep10.github.io/Fitnezz/images/logo.png]()

**Comment by Muhammad-waqar-uit** [comment]
I can do that assign it to me.

**Comment by Atharv-110** [comment]
okay sure @Muhammad-waqar-uit go for it, Assigned to you!

**Comment by SaarthakMaini** [comment]
@Atharv-110 is this issue still open for a PR?

 If yes, could you please assign it to me?
