### ISSUE TITLE
can i improve the ui of regestration form, i have checked local code is not updated and is same as in live website

### ISSUE THREAD

**Issue by vaibhavsharma1234** [Subhradeep10/Fitnezz#175]
![reges](https://user-images.githubusercontent.com/96341386/184283381-85b4d81b-7881-4361-8027-af22e3cf46f0.png)

**Comment by vaibhavsharma1234** [comment]
i have checked that there is one issue regarding https://github.com/Subhradeep10/Fitnezz/issues/163
adding more entries in form and one related to 
https://github.com/Subhradeep10/Fitnezz/issues/87 validation

**Comment by vaibhavsharma1234** [comment]
@TusharKesarwani @Atharv-110 please assign this

**Comment by TusharKesarwani** [comment]
Already assigned to someone else @vaibhavsharma1234
