### ISSUE TITLE
Add some text in the "Testimonials" section

### ISSUE THREAD

**Issue by zugzwang03** [Subhradeep10/Fitnezz#192]
Replace the dummy text in the "Testimonials" section with some relevant texts. 

I want to solve this issue under SSOC'22.

![testimonial](https://user-images.githubusercontent.com/95460021/184468688-e570bee7-4536-4ae8-89be-725863cdbfda.png)

**Comment by TusharKesarwani** [comment]
Go ahead.

**Comment by zugzwang03** [comment]
The problem is the testimonial section is not present in the recent version of the website, so how do I put text into it? @TusharKesarwani

**Comment by TusharKesarwani** [comment]
Ok
Wait for it
Another contributor is working on it

**Comment by zugzwang03** [comment]
Hey, wait I can still work on this. https://github.com/Subhradeep10/Fitnezz/pull/241 does contain dummy text, which can be changed by this issue, I was just waiting for that PR to be merged so that I can make the commits for this PR. @TusharKesarwani

**Comment by TusharKesarwani** [comment]
Ok, don't worry your PR will be merged soon.
