### ISSUE TITLE
Fix images in the page

### ISSUE THREAD

**Issue by con-artist** [Subhradeep10/Fitnezz#195]
I would like to fix all these images

![image](https://user-images.githubusercontent.com/82517773/184471438-f057bef3-5ff0-42d7-83a3-9e8be236bb8b.png)
![image](https://user-images.githubusercontent.com/82517773/184471463-a781d489-d263-45fe-a641-b05b8f06e519.png)
![image](https://user-images.githubusercontent.com/82517773/184471472-da0cabdd-c6e3-48da-abd3-ca4a90dd923e.png)

**Comment by TusharKesarwani** [comment]
Go ahead.
