### ISSUE TITLE
Aligning social media icons with logo properly & Fix the spacing in Gym schedule in Footer Section

### ISSUE THREAD

**Issue by MohitNamdev22** [Subhradeep10/Fitnezz#203]
On the Footer Section, Social Icons aren't properly aligned with the logo above and on the gym schedule, the line spacing can be improved for better visuality. Can I work on this issue?

![image](https://user-images.githubusercontent.com/89779447/184523338-842a4b21-4097-4afe-bb70-e373c0fb1361.png)

**Comment by TusharKesarwani** [comment]
This is not required here.
