### ISSUE TITLE
Modifying register your account section

### ISSUE THREAD

**Issue by nigeldias27** [Subhradeep10/Fitnezz#213]
I would like to make the width of the buttons uniform and make the icons appear. I would also like to change the color of the gradient from yellow to purple and modify the design of the input text fields. I would also like to make it more responsive for smaller screens
<img width="1303" alt="Screenshot 2022-08-15 at 6 05 50 PM" src="https://user-images.githubusercontent.com/41966681/184636195-1c9996ca-97ef-40bd-92a1-839edc847a4b.png">

**Comment by TusharKesarwani** [comment]
Go ahead
