### ISSUE TITLE
Modifying the join in section UI

### ISSUE THREAD

**Issue by ShrutiMishra-2002** [Subhradeep10/Fitnezz#214]
want to change the complete UI for this page

![Screenshot (39)](https://user-images.githubusercontent.com/87663868/184702708-ea929186-e7d5-4bc8-84a3-88c97b368f2e.png)

**Comment by ShrutiMishra-2002** [comment]
@Muhammad-waqar-uit @Subhradeep10 Please assign me this issue.

**Comment by Muhammad-waqar-uit** [comment]
I cannot assignment it because I am just a contributor.@Atharv-110 can do this.

**Comment by ShrutiMishra-2002** [comment]
@Atharv-110 please assign me this issue

**Comment by TusharKesarwani** [comment]
Go ahead
