### ISSUE TITLE
Create a Testimonials Section

### ISSUE THREAD

**Issue by zugzwang03** [Subhradeep10/Fitnezz#221]
I want to create a testimonials section for this website, just below the "Meet the Trainers" section, as it has been removed in the present version of the website.
I want to make this contribution under SSOC'22.

**Comment by Atharv-110** [comment]
Okay @zugzwang03, go for it assigned to you!
Make sure you pull the code and then push.

**Comment by zugzwang03** [comment]
kindly close this issue as completed @Atharv-110
