### ISSUE TITLE
Stock Images?

### ISSUE THREAD

**Issue by Ritvik-UX** [Subhradeep10/Fitnezz#24]
Are these stock images for sure From Pixabay or Pexels?
If no, make sure there is no attribution required.
(Copyright!)

:D

**Comment by Subhradeep10** [comment]
No no I take them from google

**Comment by Ritvik-UX** [comment]
There is high possibility of licensing issues in future... Raising new issue to replace them with stock images from [pixabay](pixabay.com) or [pexels](pexes.com).
:D
