### ISSUE TITLE
SCHEDULED CLASS Cards have some  padding issue 

### ISSUE THREAD

**Issue by Abbhiishek** [Subhradeep10/Fitnezz#245]
![image](https://user-images.githubusercontent.com/86338762/187012088-d5c41e80-f2b4-4363-888d-c96daba057bc.png)

The card's bottom button is touching the card bottom part. With some padding over the section we can fix it so that it looks like a container object

**Comment by Techkrish1** [comment]
Can you assign this to me? I will fix this issue

**Comment by TusharKesarwani** [comment]
Go ahead @Abbhiishek
