### ISSUE TITLE
Increasing Margin between the Text in the cards for better visibility on Featured Classes section

### ISSUE THREAD

**Issue by MohitNamdev22** [Subhradeep10/Fitnezz#246]
The Margin / Padding between the image & text can be improved in the cards. Can I work on this issue under SSOC'22?

![image](https://user-images.githubusercontent.com/89779447/187021920-42b0487c-b9a9-41a6-84b2-78f27247ed8f.png)

**Comment by TusharKesarwani** [comment]
Go ahead @MohitNamdev22
