### ISSUE TITLE
Add few more Trainers in the "Meet the Trainers" section 

### ISSUE THREAD

**Issue by zugzwang03** [Subhradeep10/Fitnezz#254]
The trainers section contains only 4 trainers, I want to add a few more to that set of trainers. 
I want to make this contribution under SSOC'22.

![trainers](https://user-images.githubusercontent.com/95460021/187081400-ef8bd9af-f93f-4d78-9b3e-e681ad33d717.png)

**Comment by TusharKesarwani** [comment]
Go ahead
