### ISSUE TITLE
want to add a floating (right to left) fitnezz  title above health is wealth and at the end of the page

### ISSUE THREAD

**Issue by Hittitech** [Subhradeep10/Fitnezz#256]
![2022-08-30](https://user-images.githubusercontent.com/87484115/187412463-a3dc5f3b-c9df-4ea8-bcdc-f6641c3e2723.png)

**Comment by Hittitech** [comment]
https://fitnezzz.netlify.app/index.html

**Comment by Hittitech** [comment]
@Subhradeep10

**Comment by TusharKesarwani** [comment]
This is not a good idea!!
