### ISSUE TITLE
want to add a title/heading  for pricing and plans  section  with some lines like we provide the most convinient plans for you!

### ISSUE THREAD

**Issue by Hittitech** [Subhradeep10/Fitnezz#257]
![2022-08-30 (2)](https://user-images.githubusercontent.com/87484115/187414163-209512a8-8f1b-41e8-a898-f4c89cd96682.png)

**Comment by Hittitech** [comment]
https://fitnezzz.netlify.app/index.html
@Subhradeep10

**Comment by TusharKesarwani** [comment]
Go ahead
And from next time provide a description of the issue in the comment section instead of providing it in the title

**Comment by Hittitech** [comment]
Sorry i will surely do it from next time

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
