### ISSUE TITLE
there is some spelling mistakes in the page  like carrers-careers and estabished-established will correct those and add some boldness in the required footer words

### ISSUE THREAD

**Issue by Hittitech** [Subhradeep10/Fitnezz#258]
![2022-08-30 (3)](https://user-images.githubusercontent.com/87484115/187417940-214eaa97-b279-44bf-b8a6-8f48c3652d27.png)

**Comment by Hittitech** [comment]
@Subhradeep10 
https://fitnezzz.netlify.app/index.html#

**Comment by TusharKesarwani** [comment]
Go ahead
