### ISSUE TITLE
Replace Images with Stock Ones

### ISSUE THREAD

**Issue by Ritvik-UX** [Subhradeep10/Fitnezz#26]
Replace Images with the Stock ones either from [Pixabay.com](https://pixabay.com) or [Pexels.com](https://pexels.com).

If you take image from any other source, make sure the chosen images are under Creative Commons Image License otherwise there will be copyright conflicts in future.
:D

**Comment by Subhradeep10** [comment]
@Ritvik-UX Okay , Go ahead. Assigned to u
