### ISSUE TITLE
Contact Us Page is not working.

### ISSUE THREAD

**Issue by Anubhavgupta14** [Subhradeep10/Fitnezz#275]
Contact Us Page is not working. I will Fix the link and improve the interface of contact us.

**Comment by TusharKesarwani** [comment]
It was not working because links is not added. Now, I have added the links in the navbar. If are going to change the interface then you should first explain what you are going to change in the interface.

**Comment by Anubhavgupta14** [comment]
I will change the background, colors of headlines, and add the documentation.

**Comment by TusharKesarwani** [comment]
Go ahead
