### ISSUE TITLE
About Us is not working

### ISSUE THREAD

**Issue by Anubhavgupta14** [Subhradeep10/Fitnezz#276]
About Us is not working, I will Fix the issue and improve the interface.

**Comment by Anubhavgupta14** [comment]
@TusharKesarwani @Subhradeep10 Please Assign me this issues @ #275 #273

**Comment by TusharKesarwani** [comment]
It was not working because links is not added. Now, I have added the links in the navbar. If are going to change the interface then you should first explain what you are going to change in the interface.

**Comment by Anubhavgupta14** [comment]
I have changed the Background to Animation Type Background. Please Assign it to me
