### ISSUE TITLE
Unfocused Nav Links

### ISSUE THREAD

**Issue by Ritvik-UX** [Subhradeep10/Fitnezz#28]
Basics of UI not being followed, the Nav Links are not focused when user views one of the pages. Add color to them when user is on the page for better navigation.

- Home Page > User Viewing > No Nav Link Color
![unfocused02](https://user-images.githubusercontent.com/73193822/133733171-bb0c3ef7-50d8-4356-a124-9dd516a91903.png)

- About Page > User Viewing > No Nav Link Color
![unfocused01](https://user-images.githubusercontent.com/73193822/133733413-878bd1d5-4fcb-47d5-87a9-b625c9d48592.png)
-

**Comment by Subhradeep10** [comment]
@Ritvik-UX Assigned to you, go for it
