### ISSUE TITLE
Add proper text in the 'contact' section of the website

### ISSUE THREAD

**Issue by zugzwang03** [Subhradeep10/Fitnezz#281]
I want to add some proper text in the contact page for the website.
I want to work on this issue under SSOC'22.

![contact](https://user-images.githubusercontent.com/95460021/190154216-b0f67ca2-95d5-4ad9-8e51-22bb0ba35c04.png)

**Comment by TusharKesarwani** [comment]
Go ahead

**Comment by Shoban07** [comment]
If this has been fixed , please close the issue . a gentle reminder

**Comment by zugzwang03** [comment]
yeah, this issue has been resolved in the latest version of the deployed website.
