### ISSUE TITLE
Add hovering effect on these cards in "About us" section

### ISSUE THREAD

**Issue by zugzwang03** [Subhradeep10/Fitnezz#283]
I want to add some hovering effects on these cards, like box shadow, scaling, etc.
I want to contribute on this issue under SSOC'22.

![about](https://user-images.githubusercontent.com/95460021/190382608-8f73369f-1be6-4ad9-8999-07b4a4d5e883.png)

**Comment by TusharKesarwani** [comment]
Go ahead

**Comment by zugzwang03** [comment]
kindly close this issue as completed @TusharKesarwani
