### ISSUE TITLE
I will add the Pre-Loader in the website.

### ISSUE THREAD

**Issue by Anubhavgupta14** [Subhradeep10/Fitnezz#284]
Example:-
![Loading_icon](https://user-images.githubusercontent.com/97956667/190473898-0e40cdc9-cd36-48b2-885a-824304717cae.gif)

**Comment by Anubhavgupta14** [comment]
@TusharKesarwani @Subhradeep10 Please Assign it to me

**Comment by TusharKesarwani** [comment]
Go ahead
