### ISSUE TITLE
All headings under H1 Tag | Fatal for SEO

### ISSUE THREAD

**Issue by Ritvik-UX** [Subhradeep10/Fitnezz#29]
Read this article by Search Engine Journal to get better understanding of this issue - https://www.searchenginejournal.com/h1-headings-for-google/406720/

**Comment by Subhradeep10** [comment]
@Ritvik-UX No need of SEO, we are doing it for learning,
If you want you can join @coders-community and start working there

**Comment by Ritvik-UX** [comment]
@Subhradeep10 - Yeah! Great, Thanks :D

**Comment by Ritvik-UX** [comment]
Are projects in Coders community actual, I mean not for learning :D ?
