### ISSUE TITLE
Changing the UI of contact us page

### ISSUE THREAD

**Issue by Drishti-jain21** [Subhradeep10/Fitnezz#296]
I want to change the UI of the contact us page. At present it has some placement issues and the form is simple. 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/100796147/191350752-e8b4b45f-68d6-4cc6-bfbc-eba9e7bc5c0c.png">

I want to correct the placement of location, phone and email icons.
Also, I want to add hover effect in text boxes in the form

**Comment by TusharKesarwani** [comment]
Go ahead

**Comment by HarshAg90** [comment]
hey, what kind of hover effect do you want on text boxes

**Comment by Drishti-jain21** [comment]
I want when the user clicks on the text box, it highlights
Along with that, I want to change the positioning of the form and the existing features

**Comment by HarshAg90** [comment]
I made a Pull req, please review :)

**Comment by Drishti-jain21** [comment]
But i am working on this issue

**Comment by Drishti-jain21** [comment]
@TusharKesarwani should i leave this issue and work on another issue as someone else made a PR on my issue and it has been merged

**Comment by TusharKesarwani** [comment]
Leave this issue
