### ISSUE TITLE
Fixing the links in the footer to work

### ISSUE THREAD

**Issue by Eknoor02** [Subhradeep10/Fitnezz#301]

**Comment by TusharKesarwani** [comment]
Please elaborate

**Comment by Eknoor02** [comment]
![Screenshot (202)](https://user-images.githubusercontent.com/65605024/191919343-59f80ade-e8e3-4b77-b8a1-356977197f4f.png)
The links under the your fitness are redirecting to the head of the page instead moving to the other options.

**Comment by TusharKesarwani** [comment]
Go ahead

**Comment by RohitRajvaidya5** [comment]
Is this issue resolved ? I want to contribute.

**Comment by Eknoor02** [comment]
PR for this Issue merged.
