### ISSUE TITLE
Icons in the pricing section are not showing.

### ISSUE THREAD

**Issue by codewithrabeeh** [Subhradeep10/Fitnezz#305]
Icons In the plan features is not showing. 
![image](https://user-images.githubusercontent.com/65481473/191686508-0ccdeab5-b9ca-4287-ab0c-8be1ae76479b.png)

**Comment by TusharKesarwani** [comment]
Go ahead

**Comment by codewithrabeeh** [comment]
@RobertoF90 great job!

**Comment by RobertoF90** [comment]
Happy to help!
