### ISSUE TITLE
To implement user-friendly UI at footer

### ISSUE THREAD

**Issue by Kirankp25** [Subhradeep10/Fitnezz#317]
I would like to make it a more attractive and professional view at the bottom of the site, which positively impacts the user's mind. Please assign me this issue
![Screenshot (275)](https://user-images.githubusercontent.com/87818185/192113697-6392c4a0-a03e-437b-9ee1-15ef9b824271.png)

**Comment by TusharKesarwani** [comment]
Go ahead
