### ISSUE TITLE
Update in Page Design

### ISSUE THREAD

**Issue by Subhradeep10** [Subhradeep10/Fitnezz#38]
![Fitnezz](https://user-images.githubusercontent.com/70656957/179779538-4792eee1-3b16-44f3-b564-d4282d909691.png)

**Comment by Subhradeep10** [comment]
Lind to the figma file - [Fitnezz](https://www.figma.com/file/dlJtx62xN09D8pEAwzoK4k/Gym-Fitness-Landing-Page-UX-UI--Kit-(Community)?node-id=0%3A1)

**Comment by Roshani9731** [comment]
Can I work on this? @Subhradeep10

**Comment by Aryan-Bhatt-pro** [comment]
is it still open or I can work on it too? @Subhradeep10

**Comment by Subhradeep10** [comment]
@Aryan-Bhatt-pro Sure, Do it component wise so that other participants can also do it, You do the navbar first!

**Comment by dishant-yadav** [comment]
Can I work on the hero section of the page? @Subhradeep10

**Comment by Subhradeep10** [comment]
@dishant-yadav sure, go for it
Better create another issue...I will assign it there

**Comment by dishant-yadav** [comment]
Thanks @Subhradeep10 for assigning me the work. I will surely create an another issue for the same.

**Comment by dishant-yadav** [comment]
From where can i get the assets(logo) for the page?

**Comment by Subhradeep10** [comment]
@dishant-yadav For now create a dummy logo

**Comment by dishant-yadav** [comment]
okay will be using some dummy logo.
