### ISSUE TITLE
create the footer for the page

### ISSUE THREAD

**Issue by dishant-yadav** [Subhradeep10/Fitnezz#39]
Will be adding the footer as per the design given in the figma link.

**Comment by Subhradeep10** [comment]
@dishant-yadav Sure Go ahead, I will assign you once the contruibution starts

**Comment by dishant-yadav** [comment]
Thanks @Subhradeep10

**Comment by YasirObaibullah99** [comment]
Can I create the footer of this website

**Comment by Subhradeep10** [comment]
@YasirObaibullah99 this will be assigned to someone else, once the program starts. You can try something else

**Comment by iamrahul8** [comment]
want to contribute on this project under SSOC

**Comment by Subhradeep10** [comment]
@iamrahul8 Great Rahul, Create an issue and start working on that project

**Comment by dishant-yadav** [comment]
Hi @Subhradeep10, I was assigned footer section of the website. I have almost completed the design
But in the footer section I am unable to read the text in the figma design provided and even there is logo in present in the images folder.
So I am using some random logo and putting some text where i can't understand the text
I am also attaching the ss of the footer. Check if this is fine
![Screenshot from 2022-08-09 21-50-24](https://user-images.githubusercontent.com/97543666/183721503-0ea4c2e4-9bc3-48c2-a0b0-aae6976ebe55.png)
