### ISSUE TITLE
Registration page UI imporvement

### ISSUE THREAD

**Issue by Harsh3363** [Subhradeep10/Fitnezz#40]
The registration page interface can be improved 

![Screenshot (91)](https://user-images.githubusercontent.com/72756692/182014119-2d4e0a56-b9f4-4957-b2a1-979494c971a9.png)

**Comment by Harsh3363** [comment]
Hii @Subhradeep10 please assign this to me I would like to make changes to it
Thanks

**Comment by Subhradeep10** [comment]
@Harsh3363 Assign to you

**Comment by Subhradeep10** [comment]
@Harsh3363 Go ahead, Start working on it..Assigned to you

**Comment by Harsh3363** [comment]
Sure 👍

**Comment by Anjuli08** [comment]
Can I work on this issue if its not done yet?

**Comment by TusharKesarwani** [comment]
Its already done now
