### ISSUE TITLE
Adding the description and detailed paragraph

### ISSUE THREAD

**Issue by kshitijmishra27** [Subhradeep10/Fitnezz#41]
hey @Subhradeep10 
i want to remove random paragraphs "lorem..." to some detailed and relatable data like  I can add description to paragraphs like arm day, chest day, etc

**Comment by Subhradeep10** [comment]
@kshitijmishra27 sure go for it, I will assign you once the program starts

**Comment by kshitijmishra27** [comment]
@Subhradeep10  i choosed this project sir hope you will assign me

**Comment by Subhradeep10** [comment]
@kshitijmishra27 Don't worry, I will assign you once I get excel sheet

I haven't get it yet.. You start working on it ..No issues

**Comment by Subhradeep10** [comment]
@kshitijmishra27 Go ahead, Start working on it..Assigned to you

**Comment by kshitijmishra27** [comment]
thanks sir 😁
