### ISSUE TITLE
Adding About Page

### ISSUE THREAD

**Issue by vaibhavchaubey** [Subhradeep10/Fitnezz#42]
I want to add a about page for the website

**Comment by Subhradeep10** [comment]
@vaibhavchaubey Sure, go for it...Will Assign you once the program starts

**Comment by Subhradeep10** [comment]
@vaibhavchaubey Go ahead, Start working on it..Assigned to you

**Comment by kshitijmishra27** [comment]
hey @Subhradeep10  
I recently contacted @vaibhavchaubey and he told me that he chosen another project 
so please assign me this issue  😄

**Comment by vaibhavchaubey** [comment]
@Subhradeep10 please assign this issue to @kshitijmishra27

**Comment by TusharKesarwani** [comment]
Any updates??

**Comment by TusharKesarwani** [comment]
I'm closing this issue because there is no update from your side and I'm assigning this issue to another contributor.
