### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by kshitijmishra27** [Subhradeep10/Fitnezz#44]
hey @Subhradeep10  
there is no contact page of this website so I wanted to add an attractive contact page to your website

**Comment by Subhradeep10** [comment]
@kshitijmishra27 Sure, go ahead..will assign once the contribution starts

**Comment by Aman-Singh-Kushwaha** [comment]
Hey can we work together

**Comment by kshitijmishra27** [comment]
@Aman-Singh-Kushwaha  sry bro but its individual task

**Comment by kshitijmishra27** [comment]
@Subhradeep10  hope you will assign me sir...as I choose this project in the form :)

**Comment by Subhradeep10** [comment]
@kshitijmishra27 Don't worry, I will assign it

**Comment by Aman-Singh-Kushwaha** [comment]
> @Subhradeep10 hope you will assign me sir...as I choose this project in the form :)

I too have chosen this project in the form

**Comment by Subhradeep10** [comment]
@Aman-Singh-Kushwaha No problem, The Issues are assigned on the basis of first come first serve. You can open another issue and I will assign that to you

**Comment by Subhradeep10** [comment]
@kshitijmishra27 Go ahead, Start working on it..Assigned to you

**Comment by TusharKesarwani** [comment]
Any updates??

**Comment by TusharKesarwani** [comment]
I'm closing this issue because there are no updates from your side and I'm assigning this issue to another contributor.
