### ISSUE TITLE
design the news page of the website

### ISSUE THREAD

**Issue by srinjoy-26** [Subhradeep10/Fitnezz#45]
Design the news page

**Comment by Subhradeep10** [comment]
@srinjoy-26 go ahead, will assign to you once the program starts

**Comment by Subhradeep10** [comment]
@srinjoy-26 Go ahead, Start working on it..Assigned to you

**Comment by TusharKesarwani** [comment]
Any updates??

**Comment by TusharKesarwani** [comment]
Your time is over now.
