### ISSUE TITLE
Want to design a routine page

### ISSUE THREAD

**Issue by anmol20112000** [Subhradeep10/Fitnezz#47]
This page categorized workouts on the basis of week days & also tells the sequence (sets& reps) of exercise for beginner, intermediate and pro.

**Comment by Subhradeep10** [comment]
@anmol20112000 Go ahead..will assign you once the programme starts

**Comment by Subhradeep10** [comment]
@anmol20112000 Go ahead, Start working on it..Assigned to you

**Comment by TusharKesarwani** [comment]
Any updates??

**Comment by anmol20112000** [comment]
> Any updates??

Yes just delayed due to some reason.Will generate PR in a day or two project us ready

**Comment by TusharKesarwani** [comment]
Any updates now??
