### ISSUE TITLE
Improvement in Registration Form UI

### ISSUE THREAD

**Issue by radzhiv25** [Subhradeep10/Fitnezz#48]
Will make it reponsive as well as some enhancement in UI in the form font and color

**Comment by Cypher1002** [comment]
would like to work on the issue
make it more responsive and user friendly

**Comment by Subhradeep10** [comment]
@radzhiv25 go ahead, will assign it once the program starts

**Comment by Subhradeep10** [comment]
@radzhiv25 Go ahead, Start working on it..Assigned to you
