### ISSUE TITLE
Add designing on the boxes

### ISSUE THREAD

**Issue by zugzwang03** [Subhradeep10/Fitnezz#49]
The boxes present in "Featured classes" and "Scheduled classes" can be highlighted with some box shadow and size expansion when the cursor moves into it. I wish to add this feature under SSOC'22.

**Comment by Subhradeep10** [comment]
@zugzwang03 Go ahead, will assist you once the contribution starts

**Comment by zugzwang03** [comment]
Can you please assign me here please?

**Comment by Subhradeep10** [comment]
@zugzwang03 Go ahead, Start working on it..Assigned to you

**Comment by zugzwang03** [comment]
This issue has been solved in the pull request #63

**Comment by Subhradeep10** [comment]
Great, I will merge the PR tomorrow
