### ISSUE TITLE
Create a Joining Form for the New Students

### ISSUE THREAD

**Issue by Subhradeep10** [Subhradeep10/Fitnezz#5]

**Comment by Ritvik-UX** [comment]
@Subhradeep10
What Data to be collected from visitors?
- Name
- Gender
- Age, and ?

**Comment by Subhradeep10** [comment]
@Ritvik-UX 
- Name
- Gender
- Age
- Contact Number
- Email

**Comment by Yusuf-gitCollab** [comment]
@Subhradeep10  do you only want the front end of the form? If only the front end is needed then I would like to work on it.

**Comment by Subhradeep10** [comment]
@Yusuf-gitCollab Already done. You can create other issue and work on them

**Comment by Subhradeep10** [comment]
@Yusuf-gitCollab If you want you can place the registration form inside the footer

**Comment by Ritvik-UX** [comment]
Added 😅
