### ISSUE TITLE
Improvement in navbar 

### ISSUE THREAD

**Issue by Cypher1002** [Subhradeep10/Fitnezz#50]
Navbar can be made constant so that the viewer could refer to the links without scrolling all the way up to the top

**Comment by radzhiv25** [comment]
I can work on this using Tailwind CSS

**Comment by Subhradeep10** [comment]
@Cypher1002 wanna work on it?

**Comment by Cypher1002** [comment]
Yes

**Comment by shreyashkr17** [comment]
we can make the navbar fixed on top so that user dont need to go till upward for other page links

**Comment by Subhradeep10** [comment]
@Cypher1002  Go ahead, will assign you once I get the excel sheet

**Comment by Subhradeep10** [comment]
@Cypher1002 Go ahead, Start working on it..Assigned to you
