### ISSUE TITLE
Designing chest workout page 

### ISSUE THREAD

**Issue by Cypher1002** [Subhradeep10/Fitnezz#52]
will design  full chest workout page which will include information about various workouts regarding chest muscles and making interactive links leads users towards our workout classes

**Comment by Subhradeep10** [comment]
@Cypher1002 Go ahead , will assign you once the contribution starts

**Comment by Cypher1002** [comment]
Thanks

**Comment by Subhradeep10** [comment]
@Cypher1002 Go ahead, Start working on it..Assigned to you
