### ISSUE TITLE
Arm Workout Page 

### ISSUE THREAD

**Issue by radzhiv25** [Subhradeep10/Fitnezz#53]
With the basic arm workout and minimalistic design

**Comment by Subhradeep10** [comment]
@radzhiv25 Go ahead, will assign you once the contribution starts

**Comment by Subhradeep10** [comment]
@radzhiv25 Go ahead, Start working on it..Assigned to you

**Comment by TusharKesarwani** [comment]
Any updates??

**Comment by radzhiv25** [comment]
> Any updates??

Sorry got busy 
Will update in 2-3 days

**Comment by TusharKesarwani** [comment]
I'm closing this issue
As it was already done by another contributor
And contribution phase is ending soon.
