### ISSUE TITLE
Adding Favicon on every pages

### ISSUE THREAD

**Issue by Aman-Singh-Kushwaha** [Subhradeep10/Fitnezz#54]
Hey @Subhradeep10  Can I work on adding a designed favicon on each and every connected pages

**Comment by Aman-Singh-Kushwaha** [comment]
![image](https://user-images.githubusercontent.com/96011814/182375205-7ffac5d0-0e29-41a7-b73d-605d3feaba88.png)

**Comment by Aman-Singh-Kushwaha** [comment]
Please  assign this to me

**Comment by Subhradeep10** [comment]
@Aman-Singh-Kushwaha Go ahead, will assign you once I get the excel sheet

**Comment by shreyashkr17** [comment]
can I also do the same?

**Comment by Aman-Singh-Kushwaha** [comment]
> can I also do the same?

@shreyashkr17. Bro its individual task , you can contribute to another big issue that may take longer time😊

**Comment by shreyashkr17** [comment]
okay okay . I got the point.

**Comment by Subhradeep10** [comment]
@Aman-Singh-Kushwaha Go ahead, Start working on it..Assigned to you

**Comment by Aman-Singh-Kushwaha** [comment]
@Subhradeep10  and Mentors  I have **custom designed favicon** which matches the UI color and depicts the purpose of the website

![apple-touch-icon](https://user-images.githubusercontent.com/96011814/183294852-cb656cba-8b85-46d1-a2ca-9abc2f159d97.png)

It will be clearly visible in both _Light_ and _Dark theme_ of browser

**Comment by Aman-Singh-Kushwaha** [comment]
Should i go ahead by raising PR
