### ISSUE TITLE
Adding Back to Top button

### ISSUE THREAD

**Issue by Aman-Singh-Kushwaha** [Subhradeep10/Fitnezz#55]
Back to top button get important when pages become lengthy, 
I can do this with matching color, hence ***Improving User Experience***

**Comment by Aman-Singh-Kushwaha** [comment]
Please assign it to me

**Comment by Subhradeep10** [comment]
@Aman-Singh-Kushwaha Start working on it, I will start assigning once I get the excel sheet

**Comment by Subhradeep10** [comment]
@Aman-Singh-Kushwaha Go ahead, Start working on it..Assigned to you

**Comment by TusharKesarwani** [comment]
ANy updates??

**Comment by Aman-Singh-Kushwaha** [comment]
Will finish this issue very soon

**Comment by TusharKesarwani** [comment]
Already added by another contributor
