### ISSUE TITLE
Social Media Handles should be include at footer.

### ISSUE THREAD

**Issue by Anubhavgupta14** [Subhradeep10/Fitnezz#56]
Social Media Handles and emails for contact should be included in the footer.

**Comment by Subhradeep10** [comment]
@Anubhavgupta14 Go ahead, will assign you once I get the excel sheet

**Comment by Subhradeep10** [comment]
@Anubhavgupta14 Go ahead, Start working on it..Assigned to you

**Comment by Anubhavgupta14** [comment]
Thank you @Subhradeep10 for assigning me this issue.

**Comment by Anubhavgupta14** [comment]
PR is Created

**Comment by Anubhavgupta14** [comment]
Issue has been fixed
