### ISSUE TITLE
Add Suitable Header/Title with join in page.

### ISSUE THREAD

**Issue by shreyashkr17** [Subhradeep10/Fitnezz#59]
Describe the solution you'd like

I would like to add the proper header and some attractive quote along with join in page that will be appear when the join in button will be clicked

- [x] Add attractive header Lines
- [x] Add join in page.

![s1](https://user-images.githubusercontent.com/97216718/182614748-e58eeb2e-591e-430e-858e-7ca8e18500bb.png)

**Comment by shreyashkr17** [comment]
can I resolve this issue?
@Subhradeep10 sir?

**Comment by Subhradeep10** [comment]
@shreyashkr17 Go ahead , Assigned to you
