### ISSUE TITLE
Add a subscription page/become  a member page 

### ISSUE THREAD

**Issue by shreyashkr17** [Subhradeep10/Fitnezz#60]
![s2](https://user-images.githubusercontent.com/97216718/182615591-180adcee-2ab5-4d69-97a7-17c007f81c14.png)

- [ ] add a subscription page

**Comment by shreyashkr17** [comment]
I want to resolve this issue too.

**Comment by Subhradeep10** [comment]
You want to build a page for member? @shreyashkr17

**Comment by shreyashkr17** [comment]
yes kind of subscription but that will limit to just interface not upto the redirection to payment. further you can exceed that later.

**Comment by Subhradeep10** [comment]
@shreyashkr17 Okk assigned to you

**Comment by TusharKesarwani** [comment]
I'm closing this issue
As it was already done by another contributor
And contribution phase is ending soon.
