### ISSUE TITLE
Update the Readme File

### ISSUE THREAD

**Issue by Subhradeep10** [Subhradeep10/Fitnezz#62]
- [ ] Change the logo for tech stack
- [ ] Create a stargazer's graph 
- [ ] Create a Contruibuter and Project admin section

**Comment by Muhammad-waqar-uit** [comment]
can I take this since everyone have taken all other issues.

**Comment by Subhradeep10** [comment]
@Muhammad-waqar-uit yeah go ahead, assigned to you

**Comment by Siddhanthota** [comment]
Can there be multiple assignees for this issue? If yes, i would love to explore and update the documentation.

**Comment by Subhradeep10** [comment]
@Siddhanthota No, if anything is left afterr his work if you wanna add something else in the documentation..then you can again reopen the issue

**Comment by Muhammad-waqar-uit** [comment]
@Subhradeep10 can u tell me what is that stargazer's graph? I can't find it.

**Comment by Subhradeep10** [comment]
@Muhammad-waqar-uit https://starchart.cc/ check it out

**Comment by Muhammad-waqar-uit** [comment]
@Subhradeep10  where can I see the project admins or are u the only one ?

**Comment by Subhradeep10** [comment]
Yeah , I am the only one
And project mentor are 
@Atharv-110 
@SachinMittal1766 
@TusharKesarwani
