### ISSUE TITLE
Add a Description of the coaches available to train the users

### ISSUE THREAD

**Issue by Prahmodh-R** [Subhradeep10/Fitnezz#64]

**Comment by Subhradeep10** [comment]
@Prahmodh-R Go ahead, assign to you

**Comment by Prahmodh-R** [comment]
@Subhradeep10 Thank you!

**Comment by Prahmodh-R** [comment]
This is part of SSOC '22 and mail id is pramodhr181@gmail.com.
Devfolio username: Prahmodh_Raj
