### ISSUE TITLE
Make the header/navbar stay on the top while scrolling

### ISSUE THREAD

**Issue by dhruvbhatia1** [Subhradeep10/Fitnezz#68]
Hi @Subhradeep10 
Would like to make the Header/navbar section sticky. This will keep the header on top of the webpage when you are scrolling down making the webpage better visually and the navbar easily accessible.

**Comment by Siddhanthota** [comment]
Would love to work on this one

**Comment by Subhradeep10** [comment]
@dhruvbhatia1 Not needed, It will look odd.
We are already having back to top button
