### ISSUE TITLE
Dropdown Menu in Navbar

### ISSUE THREAD

**Issue by Siddhanthota** [Subhradeep10/Fitnezz#70]
Creating a dropdown menu for Home page which will enable user to navigate to different sections of home page(For eg: Featured Classes, Scheduled Classes, Registration Section as of now). This will enhance the user experience. 
For reference:
![navbar](https://user-images.githubusercontent.com/22271775/182774313-04eeff77-de6f-4da0-8c2d-09db728c2b00.png)

**Comment by Siddhanthota** [comment]
Would love to work on this

**Comment by Subhradeep10** [comment]
@Siddhanthota No needed. The navbar is perfect

**Comment by Siddhanthota** [comment]
cool
