### ISSUE TITLE
scroll to top button

### ISSUE THREAD

**Issue by Siddhanthota** [Subhradeep10/Fitnezz#71]
creating a button that appears when you start scrolling and on click smooth scrolls you to the top of the page.

**Comment by Siddhanthota** [comment]
Here's another issue i would love to work on!!

**Comment by Subhradeep10** [comment]
@Siddhanthota Go ahead , assigned to you

**Comment by TusharKesarwani** [comment]
Any updates??

**Comment by Siddhanthota** [comment]
Working on it.

**Comment by TusharKesarwani** [comment]
> 

Ok

**Comment by zugzwang03** [comment]
> Working on it.

Are you still working on it? @Siddhanthota

**Comment by Siddhanthota** [comment]
I am stuck with a problem. I will be comfortable if @Subhradeep10 can assign it to someone else along side me

**Comment by zugzwang03** [comment]
Hey @Subhradeep10 I can work on this problem under SSOC'22, if you assign me.

**Comment by TusharKesarwani** [comment]
Go ahead @zugzwang03
