### ISSUE TITLE
FAQ and Tips section

### ISSUE THREAD

**Issue by con-artist** [Subhradeep10/Fitnezz#76]
I would also like to work on adding a Faq and workout tips section

**Comment by Atharv-110** [comment]
@con-artist Go Ahead! Assigned to you.
You can make an Accordian for Faqs and animated cards for tips.

**Comment by con-artist** [comment]
Do I have use pure javascript and css or can use some framework like bootstrap or mui?

**Comment by Atharv-110** [comment]
@con-artist
You can use framework like bootstrap but keep in mind the styling of such frameworks shouldn't override the original styling.
