### ISSUE TITLE
hero section background image is not responsive i want to make it responsive

### ISSUE THREAD

**Issue by vaibhavsharma1234** [Subhradeep10/Fitnezz#82]

**Comment by Subhradeep10** [comment]
@vaibhavsharma1234 Say it clearly with image

**Comment by vaibhavsharma1234** [comment]
![Uploading Screenshot_2022-08-04-21-10-41-848_com.android.chrome.png…]()
See this image is not responsive in mobile

**Comment by vaibhavsharma1234** [comment]
![Screenshot_2022-08-04-21-10-41-848_com android chrome](https://user-images.githubusercontent.com/96341386/182889332-63424a9b-faf4-44b8-9d8b-11de775ba97f.png)
This image is not responsive

**Comment by TusharKesarwani** [comment]
@vaibhavsharma1234 Go ahead

**Comment by vaibhavsharma1234** [comment]
this is completed 
thanks
