### ISSUE TITLE
I want to improve the ui of the cards on the main page 

### ISSUE THREAD

**Issue by vaibhavsharma1234** [Subhradeep10/Fitnezz#84]

**Comment by TusharKesarwani** [comment]
@vaibhavsharma1234 You can improve the UI, Go ahead.

**Comment by vaibhavsharma1234** [comment]
Thaks

**Comment by vaibhavsharma1234** [comment]
https://vaibhavsharma1234.github.io/demo1/
please see the changes in the cards and any other imprvement if u like 
if not then i will create a pr 
thanks

**Comment by Subhradeep10** [comment]
@vaibhavsharma1234 It's great, first pull the code cause many things are changed..and then create the PR

**Comment by vaibhavsharma1234** [comment]
Ok i wil do it by evening
