### ISSUE TITLE
Form validation 

### ISSUE THREAD

**Issue by anshulsoni4** [Subhradeep10/Fitnezz#87]
validating the registration form using javascript.

**Comment by Atharv-110** [comment]
Go Ahead @anshulsoni4! Assigned to you!

**Comment by anshulsoni4** [comment]
Hi, I need some more time for my task
will be traveling constantly, pls let me know if you can consider this

**Comment by Atharv-110** [comment]
Okay sure @anshulsoni4, make a PR before coming Monday.

**Comment by anshulsoni4** [comment]
Alright
