### ISSUE TITLE
to improve main page UI(JOIN TODAY BUTTON)

### ISSUE THREAD

**Issue by Kirankp25** [Subhradeep10/Fitnezz#88]
I want to change this main page"JOIN TODAY" button which is not visible clearly.
assign me this issue

![SSOC22](https://user-images.githubusercontent.com/87818185/182879123-1d28aa75-4599-4b7d-85c1-ac2494d3e4c1.png)

**Comment by Subhradeep10** [comment]
@Kirankp25 Already assgined to someone else
