### ISSUE TITLE
To make footer more attractive and responsive(copyright and policies)

### ISSUE THREAD

**Issue by Kirankp25** [Subhradeep10/Fitnezz#90]
In this project its footer looks very simple and basic I want to make it more attractive and add some points like "copyright and policies".
assign me this issue.

![Screenshot (208)](https://user-images.githubusercontent.com/87818185/182891713-a4838669-27e1-4837-87af-4ac1f8a2abc6.png)

**Comment by TusharKesarwani** [comment]
@Kirankp25  Already assigned to someone else.
